#!/usr/bin/env bash


export APPTAINER_BINDPATH=/uscmst1b_scratch,/cvmfs,/cvmfs/grid.cern.ch/etc/grid-security/vomses:/etc/vomses,/cvmfs/grid.cern.ch/etc/grid-security:/etc/grid-security,/tmp
export APPTAINER_CACHEDIR="/tmp/$(whoami)/apptainer_cache"
export APPTAINER_TMPDIR="/tmp/.apptainer/"

cat <<EOF > python/stats_analysis/set_cmssw.sh
source /cvmfs/cms.cern.ch/cmsset_default.sh
cd /home/cmsusr/CMSSW_11_3_4/
cmsenv  # Ignore errors
cd /home/cmsusr/coffea4bees/python/stats_analysis/
EOF

APPTAINER_SHELL=$(which bash) apptainer exec -B ${PWD}:/home/cmsusr/coffea4bees --pwd /home/cmsusr/coffea4bees/  \
  /cvmfs/unpacked.cern.ch/gitlab-registry.cern.ch/cms-analysis/general/combine-container:CMSSW_11_3_4-combine_v9.1.0-harvester_v2.1.0 \
  /bin/bash 


