FROM docker.io/snakemake/snakemake:v8.27.1

# # Create missing directory and file
RUN mkdir -p /var/lib/dpkg && touch /var/lib/dpkg/lock-frontend

RUN apt-get update -y && \
    apt-get install --no-install-recommends -y \
    git \ 
    graphviz

## install reana-client pre release with snakemake 8.20 support. Once reana-client 0.95.0 is released, this can be removed
RUN pip3 install reana-client==0.95.0a2 
RUN pip3 install panoptes-ui
