FROM condaforge/mambaforge:22.11.1-4

# python
# TODO the env.yml files should be copied to somewhere in this repo
RUN mamba env create -f https://raw.githubusercontent.com/chuyuanliu/heptools/master/docker/base.yml && mamba clean --all --yes
RUN mamba install -n hep -c conda-forge \
    # grid certificate
    ca-policy-lcg \
    # HTCondor
    htcondor \
    # XRootD
    xrootd \
    fsspec-xrootd \
    # tini
    tini \
    && mamba clean --all --yes \
    && conda run -n hep pip install --no-cache-dir \
    # DB
    dbs3-client \
    rucio-clients
RUN mamba env update -n hep -f https://raw.githubusercontent.com/chuyuanliu/heptools/master/docker/ml-cpu.yml \
    && mamba clean --all --yes
# environment
RUN touch /root/.rnd
RUN apt-get update && apt-get install -y --no-install-recommends \
    # voms
    voms-clients-java \
    # bash tools
    bash-completion \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN cat <<EOF > /etc/vomses
"cms" "voms-cms-auth.app.cern.ch" "443" "/DC=ch/DC=cern/OU=computers/CN=cms-auth.web.cern.ch" "cms"
EOF
RUN mkdir -p /etc/grid-security/vomsdir/cms/ && cat <<EOF > /etc/grid-security/vomsdir/cms/voms-cms-auth.app.cern.ch.lsc
/DC=ch/DC=cern/OU=computers/CN=cms-auth.web.cern.ch
/DC=ch/DC=cern/CN=CERN Grid Certification Authority
EOF
ENV VOMS_PROXY_INIT_DONT_VERIFY_AC=1
# rucio
RUN mkdir -p /opt/rucio/etc/
RUN wget -O /opt/rucio/etc/rucio.cfg https://raw.githubusercontent.com/dmwm/CMSRucio/820e1ab3235e9ef0d97671b7da14c8c489d08fb5/docker/rucio_client/rucio-prod.cfg
# entrypoint
RUN cat <<EOF > entrypoint.sh
eval "$(/opt/conda/bin/conda shell.bash hook)" 
conda activate hep
EOF

ENTRYPOINT ["tini", "-g", "--"]
CMD ["bash", "--init-file", "/entrypoint.sh"]