FROM coffeateam/coffea-dask:latest
#### coffea latest is ecaebc20c1d

RUN apt-get update && apt-get -y install poppler-utils
RUN pip install rucio-clients pycodestyle 

RUN mkdir -p /home/user/coffea4bees/python/
COPY python/ /home/user/coffea4bees/python/
