FROM docker.io/library/ubuntu:22.04

# Use default answers in installation commands
ENV DEBIAN_FRONTEND=noninteractive

# Use distutils provided by the standard Python library instead of the vendored one in
# setuptools, so that editable installations are stored in the right directory.
# See https://github.com/pypa/setuptools/issues/3301
ENV SETUPTOOLS_USE_DISTUTILS=stdlib

RUN apt-get update -y && \
    apt-get install --no-install-recommends -y \
    gcc \
    python3-pip \
    git \ 
    snakemake \
    graphviz

RUN pip3 install reana-client 
RUN pip3 install panoptes-ui
