FROM coffeateam/coffea-base-almalinux8:0.7.22-py3.10

RUN dnf update -y && dnf install -y poppler-utils 
RUN mamba install -y root gcc_linux-64 gxx_linux-64 compilers c-compiler cxx-compiler
RUN pip install --upgrade pip
RUN pip install pycodestyle 
RUN pip install memory-profiler
RUN pip install fsspec-xrootd

RUN mkdir -p /home/user/coffea4bees/python/
COPY python/ /home/user/coffea4bees/python/
